In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/google-reviewes/places.clean.json
/kaggle/input/google-reviewes/users.clean.json
/kaggle/input/google-reviewes/reviews.clean/reviews.clean.json


In [11]:
print(len(x))

11453845


In [12]:
final_dict = {}
for i in range(0,500000):
  d = eval(x[i])
  final_dict[i] = d

In [13]:
df1 = pd.DataFrame.from_dict(final_dict, orient ='index') 
df1.head()

rating  reviewerName                                         reviewText  \
0     3.0        an lam                                  Chất lượng tạm ổn   
1     5.0  HALİL TURGUT                              Wc si temiz duzenli..   
2     5.0         森田さとこ                   何回も私は予定に休みがセルバに行ったので覚えて見て、分かります❗   
3     5.0         森田さとこ  今度は予定に休みが登米市に行きたい❗☀😅🌌 楽しいに日帰りに登米の見学の観光(*^)(*^-...   
4     4.0         森田さとこ                            気仙沼警察署に移転中に絆 👮🐎☺🙋🚓頑張ろう❗   

                                      categories           gPlusPlaceId  \
0                              [Giải Trí - Café]  108103314380004200232   
1                              [Turkish Cuisine]  102194128241608748649   
2  [Fishing, Pond Fish Supplier, Seafood Market]  101409858828175402384   
3                                       [Museum]  101477177500158511502   
4                                       [Police]  106994170641063333085   

   unixReviewTime    reviewTime            gPlusUserId  
0    1.372687e+09   Jul 1, 2013  100000010817154263736  
1    1.342871e+09  Jul 21, 2012  100000013500285534661  
2    1.390654e+09  Jan 25, 2014  100000021336848867366  
3    1.389188e+09   Jan 8, 2014  100000021336848867366  
4    1.390486e+09  Jan 23, 2014  100000021336848867366

In [14]:
df1.tail()

rating reviewerName  \
499995     5.0       Sara S   
499996     5.0     lee dunn   
499997     5.0    Dan Walls   
499998     4.0   Tom Franck   
499999     4.0   Tom Franck   

                                               reviewText  \
499995  Por 4 meses tuve migranas diariamente y mi doc...   
499996              How thay fix up the park is excellent   
499997                    Good location fantastic service   
499998  Als student aan de universiteit Antwerpen heb ...   
499999  Een heel gezellig Italiaans restaurant met een...   

                                               categories  \
499995      [Acupuncture Clinic, Alternative Medicine...]   
499996                                             [Park]   
499997  [Cell Phone Store, Telephone Answering Service...   
499998                                             [Cafe]   
499999                               [Italian Restaurant]   

                 gPlusPlaceId  unixReviewTime    reviewTime  \
499995  114022989621522582683    1.365983e+09  Apr 14, 2013   
499996  104300504569142625511    1.338994e+09   Jun 6, 2012   
499997  100555265759855404965    1.384977e+09  Nov 20, 2013   
499998  100159548540385627163    1.346672e+09   Sep 3, 2012   
499999  104731690773370633688    1.346581e+09   Sep 2, 2012   

                  gPlusUserId  
499995  100796746104064746763  
499996  100796746479886036369  
499997  100796752288466949045  
499998  100796753323586916393  
499999  100796753323586916393

In [15]:
df1.to_pickle('./reviews_unclear_1.pkl')

In [16]:
df1.isna().sum()

rating                 0
reviewerName           0
reviewText        152694
categories         33723
gPlusPlaceId           0
unixReviewTime     28434
reviewTime         28434
gPlusUserId            0
dtype: int64

In [17]:
import pandas as pd
from scipy.sparse import csr_matrix


# Keep only the required columns
df = df1[['rating', 'gPlusUserId', 'gPlusPlaceId']]

# Drop any rows with missing values
df.dropna(inplace=True)

# Convert the IDs to integer codes
df['user_id'] = pd.factorize(df['gPlusUserId'])[0]
df['place_id'] = pd.factorize(df['gPlusPlaceId'])[0]

# Create a sparse matrix
matrix = csr_matrix((df['rating'].astype(float), (df['user_id'], df['place_id'])))

# Print the matrix
print(matrix)


/opt/conda/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":


  (0, 0)	3.0
  (1, 1)	5.0
  (2, 2)	5.0
  (2, 3)	5.0
  (2, 4)	4.0
  (2, 5)	5.0
  (2, 6)	5.0
  (2, 7)	4.0
  (2, 8)	4.0
  (2, 9)	5.0
  (2, 10)	4.0
  (2, 11)	5.0
  (3, 12)	5.0
  (4, 13)	4.0
  (4, 14)	5.0
  (4, 15)	5.0
  (4, 16)	4.0
  (4, 17)	5.0
  (4, 18)	5.0
  (5, 19)	5.0
  (6, 20)	5.0
  (7, 21)	5.0
  (8, 22)	4.0
  (9, 23)	5.0
  (9, 24)	2.0
  :	:
  (217982, 405989)	3.0
  (217982, 405990)	3.0
  (217982, 405991)	2.0
  (217982, 405992)	4.0
  (217982, 405993)	3.0
  (217983, 257089)	5.0
  (217984, 73300)	4.0
  (217984, 405994)	4.0
  (217984, 405995)	5.0
  (217985, 370031)	4.0
  (217986, 285399)	5.0
  (217987, 405996)	5.0
  (217988, 93124)	5.0
  (217989, 405997)	5.0
  (217990, 405998)	5.0
  (217991, 405999)	5.0
  (217992, 406000)	5.0
  (217993, 247094)	5.0
  (217994, 406001)	4.0
  (217995, 228889)	5.0
  (217996, 406002)	5.0
  (217997, 398861)	5.0
  (217998, 318598)	5.0
  (217999, 406003)	4.0
  (217999, 406004)	4.0


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


In [18]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between all pairs of columns in the matrix
cosine_sim = cosine_similarity(matrix.T)

# Print the cosine similarity matrix
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [19]:
type(cosine_sim)

numpy.ndarray

In [20]:
# Get a list of all unique place IDs in the dataset
unique_place_ids = df['gPlusPlaceId'].unique()

# Create a dictionary mapping each place ID to its index in the matrix
place_id_to_index = {place_id: i for i, place_id in enumerate(unique_place_ids)}

In [21]:
index_to_place_id = {v: k for k, v in place_id_to_index.items()}

In [22]:
def get_top_similar_places(place_id, k=10):
    # Get the index of the input place ID in the matrix
    place_index = place_id_to_index[place_id]
    
    # Get the cosine similarity scores between the input place and all other places
    similarity_scores = cosine_sim[place_index]
    
    # Get the indices of the top-k similar places
    top_k_indices = similarity_scores.argsort()[::-1][1:k+1]
    
    # Convert the indices back to place IDs
    top_k_places = [index_to_place_id[i] for i in top_k_indices]
    
    return top_k_places

In [23]:
place_id = '100555265759855404965'  # Example place ID
top_k_places = get_top_similar_places(place_id, k=5)  # Get top 5 similar places
print(top_k_places)  # Print the top similar places

['104731690773370633688', '101636815935876286657', '117333220974380548881', '117694279108007817890', '117756173546339350230']


In [24]:
def get_place_name(place_id):
    # Filter the original DataFrame to find the row with the specified place ID
    place = df[df['gPlusPlaceId'] == place_id].iloc[0]
    
    # Return the name of the place
    return place['name']

In [25]:
# get_place_name('100555265759855404965')

In [26]:
# print('Recommendation based on the place ',get_place_name(100555265759855404965), 'are')
# for place_is in top_k_places:
#     print(get_place_name(place_id))

## Using *reviewText* sentement

In [29]:
from textblob import TextBlob

# Define a function to perform sentiment analysis on a given text
def get_sentiment(text):
    # Create a TextBlob object for the input text
    blob = TextBlob(text)
    # Get the sentiment polarity of the text (ranging from -1 to 1)
    sentiment_polarity = blob.sentiment.polarity
    # Return the sentiment polarity
    return sentiment_polarity

# Apply the get_sentiment function to the reviewText column
df2 = df1.dropna(subset=['reviewText'])
df2['sentiment'] = df2['reviewText'].apply(get_sentiment)

# Print the first 10 rows of the updated dataframe
print(df2.head(10))

   rating  reviewerName                                         reviewText  \
0     3.0        an lam                                  Chất lượng tạm ổn   
1     5.0  HALİL TURGUT                              Wc si temiz duzenli..   
2     5.0         森田さとこ                   何回も私は予定に休みがセルバに行ったので覚えて見て、分かります❗   
3     5.0         森田さとこ  今度は予定に休みが登米市に行きたい❗☀😅🌌 楽しいに日帰りに登米の見学の観光(*^)(*^-...   
4     4.0         森田さとこ                            気仙沼警察署に移転中に絆 👮🐎☺🙋🚓頑張ろう❗   
5     5.0         森田さとこ                            久しぶりに仙台市八木山ベニーランドに乗りたい❗   
6     5.0         森田さとこ                          私は今度は休みがザ・モール★の映画に行って来ます。   
7     4.0         森田さとこ  イベントの光のページェント が素晴らしい❗🔍 私はとても仮面ライダーが素晴らしいが良いがです🎵ネ。   
8     4.0         森田さとこ                              ヒマ👽休みが仙台市科学館 に行って見ます❗   
9     5.0         森田さとこ                                     久しぶりに青葉城に行きたい❗   

                                      categories           gPlusPlaceId  \
0                              [Giải Trí - Café]  1081033143800042

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [31]:
df2.tail(10)

rating                reviewerName  \
499990     5.0            Francesca Riojas   
499991     5.0    Reynaldo Alvarez Morales   
499992     5.0              Elaina England   
499993     4.0  Jose Antonio Calles Martin   
499994     5.0            Michal Wdzieczny   
499995     5.0                      Sara S   
499996     5.0                    lee dunn   
499997     5.0                   Dan Walls   
499998     4.0                  Tom Franck   
499999     4.0                  Tom Franck   

                                               reviewText  \
499990  My Tigra loves Camp Bow Wow since the first ti...   
499991     Desde la mesa de los santos se espectacular...   
499992  My husband took his car in to be repaired and ...   
499993  La comida muy bien, y el servicio también. La ...   
499994  I called Vodotech Survaillance and they met me...   
499995  Por 4 meses tuve migranas diariamente y mi doc...   
499996              How thay fix up the park is excellent   
499997                    Good location fantastic service   
499998  Als student aan de universiteit Antwerpen heb ...   
499999  Een heel gezellig Italiaans restaurant met een...   

                                               categories  \
499990                              [Dog Day Care Center]   
499991                                               None   
499992  [Auto Body Shop, Auto Restoration Service, Car...   
499993                                     [Restaurantes]   
499994                         [Security System Supplier]   
499995      [Acupuncture Clinic, Alternative Medicine...]   
499996                                             [Park]   
499997  [Cell Phone Store, Telephone Answering Service...   
499998                                             [Cafe]   
499999                               [Italian Restaurant]   

                 gPlusPlaceId  unixReviewTime    reviewTime  \
499990  100807572136352930492    1.334174e+09  Apr 11, 2012   
499991  112067555902528656458             NaN          None   
499992  106023729584545992153    1.382198e+09  Oct 19, 2013   
499993  105386246974524985062    1.367691e+09   May 4, 2013   
499994  107775488441701676535    1.383889e+09   Nov 7, 2013   
499995  114022989621522582683    1.365983e+09  Apr 14, 2013   
499996  104300504569142625511    1.338994e+09   Jun 6, 2012   
499997  100555265759855404965    1.384977e+09  Nov 20, 2013   
499998  100159548540385627163    1.346672e+09   Sep 3, 2012   
499999  104731690773370633688    1.346581e+09   Sep 2, 2012   

                  gPlusUserId  sentiment  
499990  100796728276422459716   0.194167  
499991  100796733424101223333   0.000000  
499992  100796735910575169661   0.182937  
499993  100796739915090465352   0.000000  
499994  100796745520245136654   0.457500  
499995  100796746104064746763   0.000000  
499996  100796746479886036369   1.000000  
499997  100796752288466949045   0.550000  
499998  100796753323586916393   1.000000  
499999  100796753323586916393   0.000000

In [33]:
df1 = df1[df1['reviewText'].notnull()]

In [37]:
df1['gPlusUserId'] = df1['gPlusUserId'].astype(float)
df1['gPlusPlaceId'] = df1['gPlusPlaceId'].astype(float)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import TextBlob

# Load the data
# df = pd.read_json('/content/drive/MyDrive/RS/Assignment2-data/reviews.clean.json.gz', lines=True)

# Create a TfidfVectorizer object to extract features from the review text
tfidf = TfidfVectorizer(stop_words='english')

# Compute the tf-idf matrix
tfidf_matrix = tfidf.fit_transform(df1['reviewText'])

# Compute the sentiment score for each review
sentiment_scores = [TextBlob(text).sentiment.polarity for text in df1['reviewText']]

# Assign a weight to each review based on its sentiment score
weights = [score + 1 for score in sentiment_scores]

# Create a sparse matrix with the weighted ratings
matrix = csr_matrix((df1['rating'].astype(float) * weights, (df1['gPlusUserId'], df1['gPlusPlaceId'])))

# Compute the cosine similarity between the places
similarities = cosine_similarity(matrix)

# Define a function to get the top k similar places
def get_top_similar_places_sa(place_id, k=10):
    # Get the index of the input place ID in the matrix
    place_index = place_id_to_index[place_id]

    # Get the cosine similarity scores between the input place and all other places
    place_similarities = similarities[place_index]

    # Get the indices of the top k similar places
    top_k_indices = place_similarities.argsort()[::-1][:k]

    # Convert the indices back to place IDs
    top_k_places = [index_to_place_id[i] for i in top_k_indices]

    return top_k_places

# Define a function to get the name of a place given its ID
# def get_place_name(place_id):
#     return df.loc[df1['gPlusPlaceId'] == place_id, 'name'].iloc[0]

In [23]:
place_id = '100555265759855404965'  # Example place ID
top_k_places = get_top_similar_places_sa(place_id, k=5)  # Get top 5 similar places
print(top_k_places)  # Print the top similar places

['104731690773370633688', '101636815935876286657', '117333220974380548881', '117694279108007817890', '117756173546339350230']
